name: Deploy to AWS Lightsail

on:
    push:
        branches: ["main"]  # Cambia esto si usas otra rama

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Deploy to Lightsail
              run: |
                ssh -o StrictHostKeyChecking=no ubuntu@44.214.96.162 << 'EOF'
                cd /var/www/html
                # Eliminar todos los archivos y carpetas
                sudo rm -rf *
                # Verificar si es un repositorio git; si no, clonar
                if [ ! -d .git ]; then
                    git clone https://github.com/DAVE-PROYECTOS-UNIVALLE/PaginWeb.git .  # Clona el repositorio en el directorio actual
                fi
                git pull origin main
                # Comandos para reiniciar el servidor o mover archivos si es necesario
                EOF