name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t mi-imagen-web .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag mi-imagen-web ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen-web:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-imagen-web:latest
